version: 0.2

phases:
  pre_build:
    commands:
      - echo "Environment ready!"
      - terraform --version
      - ansible --version
      - echo "Downloading dynamic tfvars from S3..."
      - aws s3 cp s3://splunk-deployment-test/$TFVARS_S3_KEY terraform.tfvars
      - echo "Pre-build phase complete."
      
  pre_build:
    commands:
      - echo "Downloading dynamic tfvars from S3..."
      - aws s3 cp s3://splunk-deployment-test/$TFVARS_S3_KEY terraform.tfvars
      - echo "Pre-build phase complete."
      - export INSTANCE_ID=$(terraform output -raw instance_id)
      - echo $INSTANCE_ID > instance_id.txt

  build:
    commands:
      - chmod +x scripts/check_key.sh
      - terraform init
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "EC2 Splunk Deployment Completed Successfully!"
      - chmod +x scripts/stop_instance.sh
      - ./scripts/stop_instance.sh $(cat instance_id.txt)